stages:
  data_prepare:
    cmd: python -m src.stages.data_prepare --config=params.yaml
    deps:
    - src/stages/data_prepare.py
    params:
    - base
    - data_load
    outs:
    - data/processed/prepare_penguins.csv
  featurize:
    cmd: python -m src.stages.featurize --config=params.yaml
    deps:
    - data/processed/prepare_penguins.csv
    - src/stages/featurize.py
    params:
    - base
    - data_load
    - featurize
    outs:
    - data/processed/featured_penguins.csv

  data_split:
    cmd: python -m src.stages.data_split --config=params.yaml
    deps:
    - data/processed/featured_penguins.csv
    - src/stages/data_split.py
    params:
    - base
    - data_load
    - featurize
    - data_split
    outs:
    - data/processed/test_penguins.csv
    - data/processed/train_penguins.csv

  train:
    cmd: python -m src.stages.train --config=params.yaml
    deps:
    - data/processed/train_penguins.csv
    - src/stages/train.py
    outs:
    - models/model.joblib
    params:
    - base
    - data_split.trainset_path
    - featurize.target_column
    - train
artifacts:
  penguins_classifier:
    path: models/model.joblib
    type: model
    desc: This is a penguins classifier.
    labels:
    - cv
    - classification
